-- Orders Backup Created: 2026-02-03 04:02:55
-- Total Orders: 3

-- Backup of 'order' table
INSERT INTO `order` (`OrderID`, `OrderNumber`, `Customer_ID`, `SalesRep_ID`, `OrderDate`, `TotalAmount`, `Status`, `PaymentStatus`, `PaymentMethod`, `DeliveryAddress`, `SpecialInstructions`, `QuotationPDFUrl`, `ContractPDFUrl`, `ApprovedBy_SalesRep_ID`, `ApprovedBy_Admin_ID`, `Approved_Date`, `DisapprovedBy`, `DisapprovedBy_ID`, `DisapprovalReason`, `Disapproved_Date`, `CustomerNotified`, `CustomerNotified_Date`, `PreferredInstallationDate`, `OcularDate`, `FabricationDate`, `InstallationDate`, `EstimatedDelivery`, `Created_Date`, `Updated_Date`, `OrderType`, `OcularCompleted`, `OcularNotes`, `OcularCompletedBy_ID`, `FabricationStaff_ID`, `InstallationStaff_ID`, `FabricationStartDate`, `FabricationEndDate`, `ActualFabricationStartDate`, `ActualFabricationEndDate`, `FabricationProgress`, `FabricationStatus`, `FabricationNotes`, `QualityCheckNotes`, `AdminNotes`, `CustomerNotes`, `StaffNotes`, `Barcode`, `BarcodeImagePath`) VALUES ('1', 'GI001', '8', '3', '2026-01-28 03:31:27', '101285.00', 'Ready for Installation', 'Pending', NULL, '6, Sesame St., San Antonio Subd., Quezon City, Metro Manila, Philippines, 1125', '{\"contact_name\":\"Rommel John Jeric R. Lerum\",\"contact_phone\":\"09120844695\",\"contact_email\":\"lerumgops@gmail.com\",\"note\":\"I want it special\",\"preferred_ocular_date\":\"2026-02-02\"}', NULL, NULL, NULL, '2', '2026-01-27 20:53:54', NULL, NULL, NULL, NULL, '0', NULL, '2026-02-02', '2026-02-03', NULL, NULL, NULL, '2026-01-28 03:31:27', '2026-02-03 01:20:55', 'Direct', '1', NULL, '2', NULL, NULL, '2026-02-03', '2026-02-08', NULL, NULL, '75', 'Ready', NULL, NULL, NULL, 'I want it special', NULL, NULL, NULL);
INSERT INTO `order` (`OrderID`, `OrderNumber`, `Customer_ID`, `SalesRep_ID`, `OrderDate`, `TotalAmount`, `Status`, `PaymentStatus`, `PaymentMethod`, `DeliveryAddress`, `SpecialInstructions`, `QuotationPDFUrl`, `ContractPDFUrl`, `ApprovedBy_SalesRep_ID`, `ApprovedBy_Admin_ID`, `Approved_Date`, `DisapprovedBy`, `DisapprovedBy_ID`, `DisapprovalReason`, `Disapproved_Date`, `CustomerNotified`, `CustomerNotified_Date`, `PreferredInstallationDate`, `OcularDate`, `FabricationDate`, `InstallationDate`, `EstimatedDelivery`, `Created_Date`, `Updated_Date`, `OrderType`, `OcularCompleted`, `OcularNotes`, `OcularCompletedBy_ID`, `FabricationStaff_ID`, `InstallationStaff_ID`, `FabricationStartDate`, `FabricationEndDate`, `ActualFabricationStartDate`, `ActualFabricationEndDate`, `FabricationProgress`, `FabricationStatus`, `FabricationNotes`, `QualityCheckNotes`, `AdminNotes`, `CustomerNotes`, `StaffNotes`, `Barcode`, `BarcodeImagePath`) VALUES ('2', 'GI002', '8', '3', '2026-02-03 08:03:27', '131660.00', 'In Fabrication', 'Pending', NULL, '6, Sesame St., San Antonio Subd., Quezon City, Metro Manila, Philippines, 1125', '{\"contact_name\":\"Rommel John Jeric R. Lerum\",\"contact_phone\":\"09120844695\",\"contact_email\":\"lerumgops@gmail.com\",\"note\":\"\",\"preferred_ocular_date\":\"2026-02-26\"}', NULL, NULL, NULL, '2', '2026-02-03 01:03:46', NULL, NULL, NULL, NULL, '0', NULL, '2026-02-26', '2026-02-03', NULL, NULL, NULL, '2026-02-03 08:03:27', '2026-02-03 08:22:20', 'Direct', '1', NULL, '2', NULL, NULL, NULL, NULL, NULL, NULL, '0', 'Queued', NULL, NULL, NULL, '', NULL, NULL, NULL);
INSERT INTO `order` (`OrderID`, `OrderNumber`, `Customer_ID`, `SalesRep_ID`, `OrderDate`, `TotalAmount`, `Status`, `PaymentStatus`, `PaymentMethod`, `DeliveryAddress`, `SpecialInstructions`, `QuotationPDFUrl`, `ContractPDFUrl`, `ApprovedBy_SalesRep_ID`, `ApprovedBy_Admin_ID`, `Approved_Date`, `DisapprovedBy`, `DisapprovedBy_ID`, `DisapprovalReason`, `Disapproved_Date`, `CustomerNotified`, `CustomerNotified_Date`, `PreferredInstallationDate`, `OcularDate`, `FabricationDate`, `InstallationDate`, `EstimatedDelivery`, `Created_Date`, `Updated_Date`, `OrderType`, `OcularCompleted`, `OcularNotes`, `OcularCompletedBy_ID`, `FabricationStaff_ID`, `InstallationStaff_ID`, `FabricationStartDate`, `FabricationEndDate`, `ActualFabricationStartDate`, `ActualFabricationEndDate`, `FabricationProgress`, `FabricationStatus`, `FabricationNotes`, `QualityCheckNotes`, `AdminNotes`, `CustomerNotes`, `StaffNotes`, `Barcode`, `BarcodeImagePath`) VALUES ('3', 'GI003', '8', '3', '2026-02-03 08:33:08', '149660.00', '', 'Pending', NULL, '6, Sesame St., San Antonio Subd., Quezon City, Metro Manila, Philippines, 1125', '{\"contact_name\":\"Rommel John Jeric R. Lerum\",\"contact_phone\":\"09120844695\",\"contact_email\":\"lerumgops@gmail.com\",\"note\":\"\",\"preferred_ocular_date\":\"2026-02-08\"}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, '2026-02-08', NULL, NULL, NULL, NULL, '2026-02-03 08:33:08', '2026-02-03 08:33:08', 'Direct', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', 'Queued', NULL, NULL, NULL, '', NULL, NULL, NULL);

-- Backup of 'order_items' table
INSERT INTO `order_items` (`OrderItemID`, `OrderID`, `Product_ID`, `CustomizationID`, `Quantity`, `UnitPrice`, `EstimatePrice`, `Dimensions`, `GlassShape`, `GlassType`, `GlassThickness`, `EdgeWork`, `FrameType`, `Engraving`, `DesignRef`, `Created_Date`) VALUES ('1', '1', '19', '1', '0', '0.00', '0.00', 'in x in', '', '', '', '', '', 'None', 'uploads/designs/design_8_1769542268_6979127cf2ce9.png', '2026-01-28 03:31:27');
INSERT INTO `order_items` (`OrderItemID`, `OrderID`, `Product_ID`, `CustomizationID`, `Quantity`, `UnitPrice`, `EstimatePrice`, `Dimensions`, `GlassShape`, `GlassType`, `GlassThickness`, `EdgeWork`, `FrameType`, `Engraving`, `DesignRef`, `Created_Date`) VALUES ('2', '2', '18', '2', '0', '0.00', '0.00', 'in x in', '', '', '', '', '', 'None', 'uploads/designs/design_8_1770076991_69813b3fe7814.png', '2026-02-03 08:03:27');
INSERT INTO `order_items` (`OrderItemID`, `OrderID`, `Product_ID`, `CustomizationID`, `Quantity`, `UnitPrice`, `EstimatePrice`, `Dimensions`, `GlassShape`, `GlassType`, `GlassThickness`, `EdgeWork`, `FrameType`, `Engraving`, `DesignRef`, `Created_Date`) VALUES ('3', '3', '23', '3', '1', '9500.00', '149625.00', '45in x 35in', NULL, 'Clear', NULL, NULL, NULL, 'on', 'uploads/designs/design_8_1770078777_698142391bdae.png', '2026-02-03 08:33:08');
