-- Populate tag prices for product ID 16 (Black Framed Round Mirror)
INSERT INTO `product_tag_prices` (`Product_ID`, `FieldID`, `TagName`, `Price`, `Created_Date`) VALUES
(16, 'shape', 'Round', 0, NOW()),
(16, 'shape', 'Square', 0, NOW()),
(16, 'shape', 'Rectangle', 0, NOW()),
(16, 'shape', 'Oval', 200, NOW()),
(16, 'frameType', 'Frameless', 0, NOW()),
(16, 'frameType', 'Framed', 300, NOW()),
(16, 'frameColor', 'Black frame', 0, NOW()),
(16, 'frameColor', 'White frame', 100, NOW()),
(16, 'frameColor', 'Gold frame', 800, NOW()),
(16, 'frameColor', 'Silver frame', 600, NOW()),
(16, 'frameColor', 'Bronze frame', 500, NOW()),
(16, 'edgeFinish', 'Beveled', 0, NOW()),
(16, 'edgeFinish', 'Polished', 150, NOW()),
(16, 'edgeFinish', 'Rounded', 100, NOW()),
(16, 'tintFinish', 'Clear', 0, NOW()),
(16, 'tintFinish', 'Bronze tint/color', 200, NOW()),
(16, 'tintFinish', 'Gray tint/color', 200, NOW()),
(16, 'tintFinish', 'Blue tint/color', 250, NOW()),
(16, 'orientation', 'Vertical', 0, NOW()),
(16, 'orientation', 'Horizontal', 0, NOW()),
(16, 'style', 'Plain', 0, NOW()),
(16, 'style', 'French Type (grid/paneled design)', 0, NOW()),
(16, 'style', 'Beveled edges', 150, NOW()),
(16, 'mountingMethod', 'Wall-mounted', 0, NOW()),
(16, 'mountingMethod', 'Ceiling-mounted', 200, NOW()),
(16, 'control', 'Touch sensor button', 0, NOW()),
(16, 'control', 'Remote control', 300, NOW()),
(16, 'control', 'App control', 500, NOW()),
(16, 'additionalFeatures', 'Defogger', 300, NOW()),
(16, 'additionalFeatures', 'Anti-fog coating', 200, NOW()),
(16, 'additionalFeatures', 'Heated mirror', 400, NOW()),
(16, 'arrangement', 'Single', 0, NOW()),
(16, 'arrangement', 'Can be displayed as triptych', 0, NOW()),
(16, 'lighting', 'No lighting', 0, NOW()),
(16, 'lighting', 'Integrated LED lighting', 500, NOW()),
(16, 'ledColorTemperature', 'Warm white', 0, NOW()),
(16, 'ledColorTemperature', 'Cool white', 0, NOW()),
(16, 'ledColorTemperature', 'Daylight', 50, NOW()),
(16, 'gridPattern', 'No grid', 0, NOW()),
(16, 'gridPattern', 'French window style grid', 0, NOW()),
(16, 'gridPattern', 'Custom grid pattern', 200, NOW()),
(16, 'quantity', 'Single', 0, NOW()),
(16, 'quantity', 'Available in sets (3 sets, or individually)', 0, NOW());