<?php
/**
 * Add Item API Endpoint
 * Handles adding new items to the database
 */

header('Content-Type: application/json');
require_once '../config.php';

// Only allow POST requests
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Method not allowed']);
    exit;
}

// Get JSON input
$input = json_decode(file_get_contents('php://input'), true);

// If JSON input is not available, try POST data
if (!$input) {
    $input = $_POST;
}

// Validate required fields
$required_fields = ['itemName', 'itemCategory', 'initialStock', 'itemUnit'];
foreach ($required_fields as $field) {
    if (!isset($input[$field]) || empty(trim($input[$field]))) {
        http_response_code(400);
        echo json_encode(['success' => false, 'message' => "Field '$field' is required"]);
        exit;
    }
}

try {
    $conn = getDBConnection();
    
    // Prepare data
    $itemName = trim($input['itemName']);
    $category = trim($input['itemCategory']);
    $stockQuantity = intval($input['initialStock']);
    $unit = trim($input['itemUnit']);
    $isNewItem = isset($input['isNewItem']) && $input['isNewItem'] ? 1 : 0;
    $minThreshold = isset($input['minThreshold']) ? intval($input['minThreshold']) : 15;
    
    // Generate item code (will be auto-generated by trigger if NULL)
    $itemCode = null;
    
    // Insert into database
    $stmt = $conn->prepare("
        INSERT INTO items (item_code, name, category, stock_quantity, unit, min_threshold, is_new_item) 
        VALUES (?, ?, ?, ?, ?, ?, ?)
    ");
    
    if (!$stmt) {
        throw new Exception("Prepare failed: " . $conn->error);
    }
    
    $stmt->bind_param("sssisii", $itemCode, $itemName, $category, $stockQuantity, $unit, $minThreshold, $isNewItem);
    
    if ($stmt->execute()) {
        $itemId = $conn->insert_id;
        
        // Get the generated item_code
        $result = $conn->query("SELECT item_code FROM items WHERE item_id = $itemId");
        $row = $result->fetch_assoc();
        $itemCode = $row['item_code'];
        
        // Log activity to activities table
        $changeDescription = $stockQuantity . ' ' . strtolower($unit) . ' initial';
        $activityStmt = $conn->prepare("
            INSERT INTO activities (action, item_name, change_description, description, item_id) 
            VALUES (?, ?, ?, ?, ?)
        ");
        
        if ($activityStmt) {
            $action = 'Item created';
            $description = 'System';
            $activityStmt->bind_param("ssssi", $action, $itemName, $changeDescription, $description, $itemId);
            $activityStmt->execute();
            $activityStmt->close();
        }
        
        $stmt->close();
        $conn->close();
        
        // Return success response
        echo json_encode([
            'success' => true,
            'message' => 'Item added successfully',
            'data' => [
                'item_id' => $itemId,
                'item_code' => $itemCode,
                'name' => $itemName,
                'category' => $category,
                'stock_quantity' => $stockQuantity,
                'unit' => $unit,
                'is_new_item' => $isNewItem
            ]
        ]);
    } else {
        throw new Exception("Execute failed: " . $stmt->error);
    }
    
} catch (Exception $e) {
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'message' => 'Error adding item: ' . $e->getMessage()
    ]);
}

?>

