<script>
  // Pass the URLs from PHP to JS
  const baseUrl = "<?php echo base_url(); ?>";
  const getOrdersUrl = "<?php echo base_url('AdminCon/get_orders_ajax'); ?>";
  const getOrderDetailsUrl = "<?php echo base_url('AdminCon/get_order_details_ajax'); ?>";
  const getAwaitingApprovalUrl = "<?php echo base_url('AdminCon/get_awaiting_approval_orders'); ?>";
  const getApprovalOrderDetailsUrl = "<?php echo base_url('AdminCon/get_approval_order_details'); ?>";
  const approveOrderUrl = "<?php echo base_url('AdminCon/approve_order_admin'); ?>";
  const disapproveOrderUrl = "<?php echo base_url('AdminCon/disapprove_order_admin'); ?>";
  const completeOrderUrl = "<?php echo base_url('AdminCon/complete_order'); ?>";
</script>

<script src="<?php echo base_url('assets/js/admin-js/order.js'); ?>"></script>





<!-- Orders -->
<section class="order-list-section">
  <div class="section-header">
    <h2>Order <span class="found-text">16 Orders found</span></h2>

  </div>
  <div class="order-tabs">
    <div class="tab-buttons">
      <button class="tab-button active">All orders</button>
      <button class="tab-button">Completed</button>
      <button class="tab-button">Pending</button>
      <button class="tab-button">Cancel</button>
       <div class="search-container">
        <input type="text" placeholder="Search products">
        <button class="search-button">Search</button>
      </div>
    </div>

    <div class="tab-right">
     
      <div class="custom-calendar">
    <button id="calendar-btn">
        <span id="month">May</span>
        <span id="year">2025</span>
    </button>

    <div class="calendar-dropdown" id="calendar-dropdown">
        <!-- Month Selector -->
        <div class="month-selector">
            <button onclick="prevMonth()">&#8592;</button>
            <span id="dropdown-month">May</span>
            <button onclick="nextMonth()">&#8594;</button>
        </div>

        <!-- Year Selector -->
        <div class="year-selector">
            <button onclick="prevYear()">&#8592;</button>
            <span id="dropdown-year">2025</span>
            <button onclick="nextYear()">&#8594;</button>
        </div>

        <!-- Show All Button -->
        <div class="calendar-reset">
            <button id="reset-calendar">Show All</button>
        </div>
    </div>
</div>

    </div>
  </div>


  <div class="table-container">
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Order ID</th>
          <th>Product Name</th>
          <th>Address</th>
          <th>Date</th>
          <th>Price</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody id="ordersTableBody">
        <!-- Orders will be loaded dynamically via JavaScript -->
      </tbody>
    </table>
  </div>
  <div class="pagination">
    <span>Loading...</span>
    <div class="pagination-controls">
      <!-- Pagination will be generated by JavaScript -->
    </div>
  </div>
  <div id="actionMenu" class="action-menu hidden">
    <ul>
      <li><a>View</a></li>
      <li><a>Complete</a></li>
      <li><a>Cancel</a></li>
      <li><a>Delete</a></li>
    </ul>
  </div>


</section>


<!-- Order Schedule -->
<section class="order-schedule-section">
  <div class="table-container">
    <div class="section-header-schedule">
      <h2>Order Schedule Approval <img src="<?php echo base_url('assets/images/img_admin/approved.svg'); ?>"
          class="approve-img"></h2>
    </div>
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Order ID</th>
          <th>Scheduled Date</th>
          <th>Price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody id="approvalTableBody">
        <!-- Approval orders will be loaded dynamically via JavaScript -->
      </tbody>
    </table>
  </div>
  <div class="pagination">
    <span>Loading...</span>
    <div class="pagination-controls">
      <!-- Pagination will be generated by JavaScript -->
    </div>
  </div>
</section>
</main>


<!-- Popup Overlay -->
<div class="popup-overlay" id="orderPopup">
  <div class="popup">
    <span class="close-btn" id="closePopup">&times;</span>
    <h3>Order Details</h3>

    <table class="order-details" id="orderDetailsTable">
      <tbody>
        <tr>
          <td>Order ID:</td>
          <td id="popup-order-id">-</td>
        </tr>
        <tr>
          <td>Product:</td>
          <td id="popup-product-name">-</td>
        </tr>
        <tr>
          <td>Address:</td>
          <td id="popup-address">-</td>
        </tr>
        <tr>
          <td>Date:</td>
          <td id="popup-date">-</td>
        </tr>
        <tr>
          <td>Status:</td>
          <td id="popup-status">-</td>
        </tr>
        <tr>
          <td>Shape:</td>
          <td id="popup-shape">-</td>
        </tr>
        <tr>
          <td>Dimension:</td>
          <td id="popup-dimension">-</td>
        </tr>
        <tr>
          <td>Type:</td>
          <td id="popup-type">-</td>
        </tr>
        <tr>
          <td>Thickness:</td>
          <td id="popup-thickness">-</td>
        </tr>
        <tr>
          <td>Edge Work:</td>
          <td id="popup-edge-work">-</td>
        </tr>
        <tr>
          <td>Frame Type:</td>
          <td id="popup-frame-type">-</td>
        </tr>
        <tr>
          <td>Engraving:</td>
          <td id="popup-engraving">-</td>
        </tr>
        <tr>
          <td>File Attached:</td>
          <td id="popup-file-attached">-</td>
        </tr>
        <tr>
          <td>Total Quotation (₱):</td>
          <td id="popup-total-quotation">-</td>
        </tr>
        <tr>
          <td>Preferred Installation Date:</td>
          <td id="popup-preferred-installation-date">-</td>
        </tr>
      </tbody>
    </table>

    <div class="barcode" id="popup-barcode">
      <img id="barcode-img" src="" alt="Barcode">
    </div>

    <button class="export-btn">Export</button>
    <button class="approve-btn" id="popup-approve-btn" style="display:none;">Approve Order</button>
    <button class="disapprove-btn" id="popup-disapprove-btn" style="display:none;">Disapprove Order</button>

  </div>
</div>

<!-- Approval Review Popup Overlay -->
<div class="popup-overlay" id="approvalPopup">
  <div class="popup">
    <span class="close-btn" id="closeApprovalPopup">&times;</span>
    <h3>Review Order for Approval</h3>

    <table class="order-details" id="approvalDetailsTable">
      <tbody>
        <tr>
          <td>Order ID:</td>
          <td id="approval-order-id">-</td>
        </tr>
        <tr>
          <td>Product:</td>
          <td id="approval-product-name">-</td>
        </tr>
        <tr>
          <td>Customer:</td>
          <td id="approval-customer-name">-</td>
        </tr>
        <tr>
          <td>Sales Rep:</td>
          <td id="approval-sales-rep-name">-</td>
        </tr>
        <tr>
          <td>Address:</td>
          <td id="approval-address">-</td>
        </tr>
        <tr>
          <td>Order Date:</td>
          <td id="approval-order-date">-</td>
        </tr>
        <tr>
          <td>Scheduled Date:</td>
          <td id="approval-scheduled-date">-</td>
        </tr>
        <tr>
          <td>Requested Date:</td>
          <td id="approval-requested-date">-</td>
        </tr>
        <tr>
          <td>Shape:</td>
          <td id="approval-shape">-</td>
        </tr>
        <tr>
          <td>Dimension:</td>
          <td id="approval-dimension">-</td>
        </tr>
        <tr>
          <td>Type:</td>
          <td id="approval-type">-</td>
        </tr>
        <tr>
          <td>Thickness:</td>
          <td id="approval-thickness">-</td>
        </tr>
        <tr>
          <td>Edge Work:</td>
          <td id="approval-edge-work">-</td>
        </tr>
        <tr>
          <td>Frame Type:</td>
          <td id="approval-frame-type">-</td>
        </tr>
        <tr>
          <td>Engraving:</td>
          <td id="approval-engraving">-</td>
        </tr>
        <tr>
          <td>File Attached:</td>
          <td id="approval-file-attached">-</td>
        </tr>
        <tr>
          <td>Total Quotation (₱):</td>
          <td id="approval-total-quotation">-</td>
        </tr>
      </tbody>
    </table>

    <div class="barcode" id="approval-barcode">
      <img id="approval-barcode-img" src="" alt="Barcode">
    </div>

    <div class="approval-actions">
      <div class="form-group">
        <label for="admin-notes">Admin Notes (Optional):</label>
        <textarea id="admin-notes" placeholder="Add any notes for the sales representative..."></textarea>
      </div>
      <div class="form-group">
        <label for="disapproval-reason">Disapproval Reason (Required if disapproving):</label>
        <textarea id="disapproval-reason" placeholder="Enter reason for disapproval..."></textarea>
      </div>
      <div class="popup-actions">
        <button class="approve-btn" id="approval-approve-btn">Approve Order</button>
        <button class="disapprove-btn" id="approval-disapprove-btn">Disapprove Order</button>
        <button class="cancel-btn" id="approval-cancel-btn">Cancel</button>
      </div>
    </div>

  </div>
</div>

