<script>
  // Pass the URLs from PHP to JS
  const baseUrl = "<?php echo base_url(); ?>";
  const getOrdersUrl = "<?php echo base_url('AdminCon/get_orders_ajax'); ?>";
  const getOrderDetailsUrl = "<?php echo base_url('AdminCon/get_order_details_ajax'); ?>";
  const getAwaitingApprovalUrl = "<?php echo base_url('AdminCon/get_awaiting_approval_orders'); ?>";
  const getApprovalOrderDetailsUrl = "<?php echo base_url('AdminCon/get_approval_order_details'); ?>";
  const approveOrderUrl = "<?php echo base_url('AdminCon/approve_order_admin'); ?>";
  const disapproveOrderUrl = "<?php echo base_url('AdminCon/disapprove_order_admin'); ?>";
  const completeOrderUrl = "<?php echo base_url('AdminCon/complete_order'); ?>";
</script>

<script src="<?php echo base_url('assets/js/admin-js/order.js'); ?>"></script>





<!-- Orders -->
<section class="order-list-section">
  <div class="section-header">
    <h2>Order <span class="found-text">16 Orders found</span></h2>

  </div>
  <div class="order-tabs">
    <div class="tab-buttons">
      <button class="tab-button active">All orders</button>
      <button class="tab-button">Completed</button>
      <button class="tab-button">Pending</button>
      <button class="tab-button">Cancel</button>
       <div class="search-container">
        <input type="text" placeholder="Search products">
        <button class="search-button">Search</button>
      </div>
    </div>

    <div class="tab-right">
     
      <div class="custom-calendar">
    <button id="calendar-btn">
        <span id="month">May</span>
        <span id="year">2025</span>
    </button>

    <div class="calendar-dropdown" id="calendar-dropdown">
        <!-- Month Selector -->
        <div class="month-selector">
            <button onclick="prevMonth()">&#8592;</button>
            <span id="dropdown-month">May</span>
            <button onclick="nextMonth()">&#8594;</button>
        </div>

        <!-- Year Selector -->
        <div class="year-selector">
            <button onclick="prevYear()">&#8592;</button>
            <span id="dropdown-year">2025</span>
            <button onclick="nextYear()">&#8594;</button>
        </div>

        <!-- Show All Button -->
        <div class="calendar-reset">
            <button id="reset-calendar">Show All</button>
        </div>
    </div>
</div>

    </div>
  </div>


  <div class="table-container">
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Order ID</th>
          <th>Product Name</th>
          <th>Address</th>
          <th>Date</th>
          <th>Price</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody id="ordersTableBody">
        <!-- Orders will be loaded dynamically via JavaScript -->
      </tbody>
    </table>
  </div>
  <div class="pagination">
    <span>Loading...</span>
    <div class="pagination-controls">
      <!-- Pagination will be generated by JavaScript -->
    </div>
  </div>
  <div id="actionMenu" class="action-menu hidden">
    <ul>
      <li><a>View</a></li>
      <li><a>Complete</a></li>
      <li><a>Cancel</a></li>
      <li><a>Delete</a></li>
    </ul>
  </div>


</section>


<!-- Order Schedule -->
<section class="order-schedule-section">
  <div class="table-container">
    <div class="section-header-schedule">
      <h2>Order Schedule Approval <img src="<?php echo base_url('assets/images/img_admin/approved.svg'); ?>"
          class="approve-img"></h2>
    </div>
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Order ID</th>
          <th>Scheduled Date</th>
          <th>Price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody id="approvalTableBody">
        <!-- Approval orders will be loaded dynamically via JavaScript -->
      </tbody>
    </table>
  </div>
  <div class="pagination">
    <span>Loading...</span>
    <div class="pagination-controls">
      <!-- Pagination will be generated by JavaScript -->
    </div>
  </div>
</section>
</main>


<!-- Popup Overlay -->
<div class="popup-overlay" id="orderPopup">
  <div class="popup">
    <span class="close-btn" id="closePopup">&times;</span>
    <h3>Order Details</h3>

    <table class="order-details" id="orderDetailsTable">
      <tbody>
        <tr>
          <td>Order ID:</td>
          <td id="popup-order-id">-</td>
        </tr>
        <tr>
          <td>Product:</td>
          <td id="popup-product-name">-</td>
        </tr>
        <tr>
          <td>Address:</td>
          <td id="popup-address">-</td>
        </tr>
        <tr>
          <td>Date:</td>
          <td id="popup-date">-</td>
        </tr>
        <tr>
          <td>Status:</td>
          <td id="popup-status">-</td>
        </tr>
        <tr>
          <td>Shape:</td>
          <td id="popup-shape">-</td>
        </tr>
        <tr>
          <td>Dimension:</td>
          <td id="popup-dimension">-</td>
        </tr>
        <tr>
          <td>Type:</td>
          <td id="popup-type">-</td>
        </tr>
        <tr>
          <td>Thickness:</td>
          <td id="popup-thickness">-</td>
        </tr>
        <tr>
          <td>Edge Work:</td>
          <td id="popup-edge-work">-</td>
        </tr>
        <tr>
          <td>Frame Type:</td>
          <td id="popup-frame-type">-</td>
        </tr>
        <tr>
          <td>Engraving:</td>
          <td id="popup-engraving">-</td>
        </tr>
        <tr>
          <td>File Attached:</td>
          <td>
            <div style="display: flex; align-items: center; gap: 10px;">
              <div id="popup-file-thumbnail" style="display: none;">
                <img id="popup-file-thumbnail-img" src="" alt="Design Thumbnail" style="width: 80px; height: 80px; object-fit: cover; border-radius: 4px; border: 1px solid #ddd; cursor: pointer;" onclick="window.open(this.src, '_blank')">
              </div>
              <div style="flex: 1;">
                <a href="#" id="popup-file-attached-link" target="_blank" style="display: none; color: #0066cc; text-decoration: underline;">-</a>
                <span id="popup-file-attached-text" style="display: none;">-</span>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>Total Quotation (₱):</td>
          <td id="popup-total-quotation">-</td>
        </tr>
        <tr>
          <td>Preferred Installation Date:</td>
          <td id="popup-preferred-installation-date">-</td>
        </tr>
      </tbody>
    </table>

    <div class="barcode" id="popup-barcode">
      <img id="barcode-img" src="" alt="Barcode">
    </div>

    <button class="export-btn">Export</button>
    <button class="approve-btn" id="popup-approve-btn" style="display:none;">Approve Order</button>
    <button class="disapprove-btn" id="popup-disapprove-btn" style="display:none;">Disapprove Order</button>

  </div>
</div>

<!-- Approval Review Popup Overlay -->
<div class="popup-overlay" id="approvalPopup">
  <div class="popup modern-popup">
    <span class="close-btn" id="closeApprovalPopup">&times;</span>
    
    <div class="popup-header-modern">
      <h3 class="popup-title-modern">Review Order for Approval</h3>
      <p class="popup-subtitle">Review and approve or disapprove this order</p>
    </div>

    <div class="popup-content-modern">
      <!-- Order & Customer Info Card -->
      <div class="info-card">
        <div class="info-card-header">
          <span class="info-card-icon">📋</span>
          <h4 class="info-card-title">Order & Customer Information</h4>
        </div>
        <div class="info-card-body">
          <div class="info-grid">
            <div class="info-item">
              <span class="info-label">Order ID</span>
              <span class="info-value" id="approval-order-id">-</span>
            </div>
            <div class="info-item">
              <span class="info-label">Product</span>
              <span class="info-value" id="approval-product-name">-</span>
            </div>
            <div class="info-item">
              <span class="info-label">Customer</span>
              <span class="info-value" id="approval-customer-name">-</span>
            </div>
            <div class="info-item">
              <span class="info-label">Sales Rep</span>
              <span class="info-value" id="approval-sales-rep-name">-</span>
            </div>
            <div class="info-item">
              <span class="info-label">Order Date</span>
              <span class="info-value" id="approval-order-date">-</span>
            </div>
            <div class="info-item">
              <span class="info-label">Scheduled Date</span>
              <span class="info-value" id="approval-scheduled-date">-</span>
            </div>
            <div class="info-item">
              <span class="info-label">Requested Date</span>
              <span class="info-value" id="approval-requested-date">-</span>
            </div>
            <div class="info-item full-width">
              <span class="info-label">Address</span>
              <span class="info-value" id="approval-address">-</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Customization Card -->
      <div class="info-card">
        <div class="info-card-header">
          <span class="info-card-icon">⚙️</span>
          <h4 class="info-card-title">Customization Details</h4>
        </div>
        <div class="info-card-body">
          <div class="info-grid">
            <div class="info-item">
              <span class="info-label">Shape</span>
              <span class="info-value" id="approval-shape">-</span>
            </div>
            <div class="info-item">
              <span class="info-label">Dimension</span>
              <span class="info-value" id="approval-dimension">-</span>
            </div>
            <div class="info-item">
              <span class="info-label">Type</span>
              <span class="info-value" id="approval-type">-</span>
            </div>
            <div class="info-item">
              <span class="info-label">Thickness</span>
              <span class="info-value" id="approval-thickness">-</span>
            </div>
            <div class="info-item">
              <span class="info-label">Edge Work</span>
              <span class="info-value" id="approval-edge-work">-</span>
            </div>
            <div class="info-item">
              <span class="info-label">Frame Type</span>
              <span class="info-value" id="approval-frame-type">-</span>
            </div>
            <div class="info-item">
              <span class="info-label">Engraving</span>
              <span class="info-value" id="approval-engraving">-</span>
            </div>
            <div class="info-item full-width">
              <span class="info-label">File Attached</span>
              <div class="file-attachment-modern">
                <div id="approval-file-thumbnail" class="file-thumbnail-modern" style="display: none;">
                  <img id="approval-file-thumbnail-img" src="" alt="Design Thumbnail" onclick="window.open(this.src, '_blank')">
                </div>
                <div class="file-link-modern">
                  <a href="#" class="file-link" id="approval-file-attached-link" target="_blank" style="display: none;">-</a>
                  <span class="file-text" id="approval-file-attached-text" style="display: none;">-</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Total Card -->
      <div class="info-card">
        <div class="info-card-header">
          <span class="info-card-icon">💰</span>
          <h4 class="info-card-title">Total Quotation</h4>
        </div>
        <div class="info-card-body">
          <div class="total-section-modern">
            <span class="total-label">Total Amount</span>
            <span class="total-amount" id="approval-total-quotation">₱0.00</span>
          </div>
        </div>
      </div>

      <!-- Barcode Card -->
      <div class="info-card" id="approval-barcode" style="display: none;">
        <div class="info-card-header">
          <span class="info-card-icon">📊</span>
          <h4 class="info-card-title">Order Barcode</h4>
        </div>
        <div class="info-card-body barcode-body-modern">
          <img id="approval-barcode-img" src="" alt="Barcode" class="barcode-img-modern">
        </div>
      </div>

      <!-- Admin Notes & Actions Card -->
      <div class="info-card">
        <div class="info-card-header">
          <span class="info-card-icon">📝</span>
          <h4 class="info-card-title">Admin Notes & Actions</h4>
        </div>
        <div class="info-card-body">
          <div class="form-group-modern">
            <label for="admin-notes" class="form-label-modern">Admin Notes (Optional)</label>
            <textarea id="admin-notes" class="form-textarea-modern" placeholder="Add any notes for the sales representative..."></textarea>
          </div>
          <div class="form-group-modern">
            <label for="disapproval-reason" class="form-label-modern">Disapproval Reason <span class="required-asterisk">*</span></label>
            <textarea id="disapproval-reason" class="form-textarea-modern" placeholder="Enter reason for disapproval (required if disapproving)..."></textarea>
          </div>
        </div>
      </div>
    </div>

    <div class="popup-actions-modern">
      <button class="btn-modern btn-secondary" id="approval-cancel-btn" type="button">Cancel</button>
      <button class="btn-modern btn-danger" id="approval-disapprove-btn" type="button">Disapprove Order</button>
      <button class="btn-modern btn-success" id="approval-approve-btn" type="button">Approve Order</button>
    </div>
  </div>
</div>

