<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>

<script>
  const baseUrl = "<?php echo base_url(); ?>";
  const getQuotationsUrl = "<?php echo base_url('AdminCon/get_quotations_ajax'); ?>";
  const getQuotationDetailsUrl = "<?php echo base_url('AdminCon/get_quotation_details_ajax'); ?>";
  const approveQuotationUrl = "<?php echo base_url('AdminCon/approve_quotation'); ?>";
  const rejectQuotationUrl = "<?php echo base_url('AdminCon/reject_quotation'); ?>";
  const convertToOrderUrl = "<?php echo base_url('AdminCon/convert_quotation_to_order'); ?>";
  const getSalesRepsUrl = "<?php echo base_url('AdminCon/get_sales_reps_ajax'); ?>";
</script>

<script src="<?php echo base_url('assets/js/admin-js/quotations.js'); ?>"></script>

<!-- Quotations Section -->
<section class="order-management-section">
  <div class="section-header">
    <h2>Quotations <span class="found-text">Loading...</span></h2>
  </div>

  <!-- Filters Section -->
  <div class="filters-container">
    <div class="filter-group">
      <label for="status-filter">Status:</label>
      <select id="status-filter" class="filter-select">
        <option value="all">All</option>
        <option value="Pending">Pending</option>
        <option value="Approved">Approved</option>
        <option value="Rejected">Rejected</option>
        <option value="Converted to Order">Converted to Order</option>
      </select>
    </div>
    <div class="filter-group">
      <label for="date-range-start">Date Range:</label>
      <input type="date" id="date-range-start" class="filter-input">
      <span>to</span>
      <input type="date" id="date-range-end" class="filter-input">
    </div>
    <div class="filter-group">
      <label for="client-search">Client:</label>
      <input type="text" id="client-search" class="filter-input" placeholder="Name, email, or phone">
    </div>
    <div class="filter-group">
      <label for="sales-rep-filter">Sales Rep:</label>
      <select id="sales-rep-filter" class="filter-select">
        <option value="all">All</option>
        <!-- Options will be loaded via AJAX -->
      </select>
    </div>
    <div class="filter-group">
      <label for="amount-min">Amount Range:</label>
      <input type="number" id="amount-min" class="filter-input" placeholder="Min" step="0.01">
      <span>to</span>
      <input type="number" id="amount-max" class="filter-input" placeholder="Max" step="0.01">
    </div>
    <button class="filter-btn" id="apply-filters">Apply Filters</button>
    <button class="filter-btn filter-btn-secondary" id="clear-filters">Clear</button>
  </div>

  <!-- Quotations Table -->
  <div class="table-container">
    <table class="orders-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Quotation ID</th>
          <th>Client</th>
          <th>Sales Rep</th>
          <th>Product</th>
          <th>Amount</th>
          <th>Date Created</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody id="quotationsTableBody">
        <tr>
          <td colspan="9" style="text-align: center; padding: 20px;">Loading quotations...</td>
        </tr>
      </tbody>
    </table>
  </div>

  <!-- Pagination -->
  <div class="pagination">
    <span id="pagination-info">Loading...</span>
    <div class="pagination-controls" id="pagination-controls">
      <!-- Pagination will be generated by JavaScript -->
    </div>
  </div>
</section>

<!-- Quotation Details Modal -->
<div class="popup-overlay" id="quotationDetailsModal">
  <div class="popup popup-large">
    <span class="close-btn" id="closeQuotationDetails">&times;</span>
    <h3 class="popup-title">Quotation Details</h3>

    <div class="order-details-content">
      <!-- 1. Quotation Information Section -->
      <div class="details-section">
        <h4 class="section-title">Quotation Information</h4>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">Quotation ID:</span>
            <span class="info-value" id="detail-quotation-id">-</span>
          </div>
          <div class="info-item">
            <span class="info-label">Date Created:</span>
            <span class="info-value" id="detail-created-date">-</span>
          </div>
          <div class="info-item">
            <span class="info-label">Valid Until:</span>
            <span class="info-value" id="detail-expiry-date">-</span>
          </div>
          <div class="info-item">
            <span class="info-label">Status:</span>
            <span class="info-value">
              <span class="badge" id="detail-status-badge">-</span>
            </span>
          </div>
          <div class="info-item">
            <span class="info-label">Sales Representative:</span>
            <span class="info-value" id="detail-sales-rep">-</span>
          </div>
        </div>
      </div>

      <!-- 2. Customer Information Section -->
      <div class="details-section">
        <h4 class="section-title">Customer Information</h4>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">Customer Name:</span>
            <span class="info-value" id="detail-customer-name">-</span>
          </div>
          <div class="info-item">
            <span class="info-label">Email:</span>
            <span class="info-value" id="detail-customer-email">-</span>
          </div>
          <div class="info-item">
            <span class="info-label">Phone:</span>
            <span class="info-value" id="detail-customer-phone">-</span>
          </div>
          <div class="info-item full-width">
            <span class="info-label">Address:</span>
            <span class="info-value" id="detail-customer-address">-</span>
          </div>
        </div>
      </div>

      <!-- 3. Items/Products Section -->
      <div class="details-section">
        <h4 class="section-title">Items/Products</h4>
        <table class="items-table">
          <thead>
            <tr>
              <th>Product Name</th>
              <th>Specifications</th>
              <th>Quantity</th>
              <th>Unit Price</th>
              <th>Subtotal</th>
            </tr>
          </thead>
          <tbody id="detail-items-tbody">
            <!-- Items will be loaded here -->
          </tbody>
        </table>
        <div class="info-grid" style="margin-top: 15px;">
          <div class="info-item">
            <span class="info-label">Total Amount:</span>
            <span class="info-value info-value-bold" id="detail-total-amount">₱0.00</span>
          </div>
        </div>
      </div>

      <!-- 4. Admin Actions Section -->
      <div class="details-section">
        <h4 class="section-title">Admin Actions</h4>
        <div class="action-buttons">
          <div class="action-buttons-row">
            <button class="btn-primary" id="approve-quotation-btn">Approve Quotation</button>
            <button class="btn-danger" id="reject-quotation-btn">Reject Quotation</button>
            <button class="btn-success" id="convert-to-order-btn">Convert to Order</button>
            <button class="btn-secondary" id="view-print-btn">View/Print</button>
            <button class="btn-secondary" id="send-to-customer-btn">Send to Customer</button>
          </div>
          <div class="action-group" style="margin-top: 15px;">
            <label for="admin-notes-textarea">Admin Notes:</label>
            <textarea id="admin-notes-textarea" class="form-control" rows="3" placeholder="Add internal notes..."></textarea>
            <button class="btn-primary" id="save-notes-btn" style="margin-top: 8px;">Save Notes</button>
          </div>
          <div id="rejection-reason-group" style="display: none; margin-top: 15px;">
            <label for="rejection-reason-textarea">Rejection Reason:</label>
            <textarea id="rejection-reason-textarea" class="form-control" rows="3" placeholder="Enter reason for rejection..." required></textarea>
            <button class="btn-danger" id="confirm-reject-btn" style="margin-top: 8px;">Confirm Rejection</button>
          </div>
          <div id="linked-order-info" style="display: none; margin-top: 15px; padding: 10px; background: #e7f3ff; border-radius: 4px;">
            <span class="info-label">Linked Order:</span>
            <a href="#" id="linked-order-link" class="order-link" target="_blank">-</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Action Menu Dropdown -->
<div id="actionMenu" class="action-menu hidden">
  <ul>
    <li><a href="#" class="action-view">View Details</a></li>
    <li><a href="#" class="action-approve">Approve</a></li>
    <li><a href="#" class="action-reject">Reject</a></li>
    <li><a href="#" class="action-convert">Convert to Order</a></li>
    <li><a href="#" class="action-export">Export PDF</a></li>
  </ul>
</div>
