<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>

<script>
  const baseUrl = "<?php echo base_url(); ?>";
  const getReturnOrdersUrl = "<?php echo base_url('AdminCon/get_return_orders_ajax'); ?>";
  const getReturnDetailsUrl = "<?php echo base_url('AdminCon/get_return_details_ajax'); ?>";
  const approveReturnUrl = "<?php echo base_url('AdminCon/approve_return'); ?>";
  const rejectReturnUrl = "<?php echo base_url('AdminCon/reject_return'); ?>";
  const processRefundUrl = "<?php echo base_url('AdminCon/process_refund'); ?>";
  const createReplacementOrderUrl = "<?php echo base_url('AdminCon/create_replacement_order'); ?>";
  const scheduleReplacementUrl = "<?php echo base_url('AdminCon/schedule_replacement_appointment'); ?>";
  const updateReturnStatusUrl = "<?php echo base_url('AdminCon/update_return_status'); ?>";
</script>

<script src="<?php echo base_url('assets/js/admin-js/return-orders.js'); ?>"></script>

<!-- Return Orders Section -->
<section class="order-management-section">
  <div class="section-header">
    <h2>Return Orders <span class="found-text">Loading...</span></h2>
  </div>

  <!-- Filters Section -->
  <div class="filters-container">
    <div class="filter-group">
      <label for="status-filter">Status:</label>
      <select id="status-filter" class="filter-select">
        <option value="all">All</option>
        <option value="Pending">Pending</option>
        <option value="Approved">Approved</option>
        <option value="Rejected">Rejected</option>
        <option value="Processing">Processing</option>
        <option value="Completed">Completed</option>
      </select>
    </div>
    <div class="filter-group">
      <label for="date-range-start">Date Range:</label>
      <input type="date" id="date-range-start" class="filter-input">
      <span>to</span>
      <input type="date" id="date-range-end" class="filter-input">
    </div>
    <div class="filter-group">
      <label for="client-search">Client:</label>
      <input type="text" id="client-search" class="filter-input" placeholder="Name, email, or phone">
    </div>
    <div class="filter-group">
      <label for="order-search">Original Order:</label>
      <input type="text" id="order-search" class="filter-input" placeholder="Order number">
    </div>
    <div class="filter-group">
      <label for="return-type-filter">Return Type:</label>
      <select id="return-type-filter" class="filter-select">
        <option value="all">All</option>
        <option value="Defect">Defect</option>
        <option value="Wrong Item">Wrong Item</option>
        <option value="Customer Request">Customer Request</option>
        <option value="Other">Other</option>
      </select>
    </div>
    <button class="filter-btn" id="apply-filters">Apply Filters</button>
    <button class="filter-btn filter-btn-secondary" id="clear-filters">Clear</button>
  </div>

  <!-- Return Orders Table -->
  <div class="table-container">
    <table class="orders-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Return ID</th>
          <th>Original Order</th>
          <th>Client</th>
          <th>Product</th>
          <th>Return Date</th>
          <th>Reason</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody id="returnOrdersTableBody">
        <tr>
          <td colspan="9" style="text-align: center; padding: 20px;">Loading return orders...</td>
        </tr>
      </tbody>
    </table>
  </div>

  <!-- Pagination -->
  <div class="pagination">
    <span id="pagination-info">Loading...</span>
    <div class="pagination-controls" id="pagination-controls">
      <!-- Pagination will be generated by JavaScript -->
    </div>
  </div>
</section>

<!-- Return Order Details Modal -->
<div class="popup-overlay" id="returnOrderDetailsModal">
  <div class="popup popup-large">
    <span class="close-btn" id="closeReturnDetails">&times;</span>
    <h3 class="popup-title">Return Order Details</h3>

    <div class="order-details-content">
      <!-- 1. Return Information Section -->
      <div class="details-section">
        <h4 class="section-title">Return Information</h4>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">Return ID:</span>
            <span class="info-value" id="detail-return-id">-</span>
          </div>
          <div class="info-item">
            <span class="info-label">Return Date:</span>
            <span class="info-value" id="detail-return-date">-</span>
          </div>
          <div class="info-item">
            <span class="info-label">Status:</span>
            <span class="info-value">
              <span class="badge" id="detail-status-badge">-</span>
            </span>
          </div>
          <div class="info-item">
            <span class="info-label">Return Type:</span>
            <span class="info-value" id="detail-return-type">-</span>
          </div>
        </div>
      </div>

      <!-- 2. Original Order Information Section (Read-only, Linked) -->
      <div class="details-section">
        <h4 class="section-title">Original Order Information</h4>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">Order Number:</span>
            <span class="info-value">
              <a href="#" id="detail-original-order-link" class="order-link" target="_blank">-</a>
            </span>
          </div>
          <div class="info-item">
            <span class="info-label">Order Date:</span>
            <span class="info-value" id="detail-original-order-date">-</span>
          </div>
          <div class="info-item">
            <span class="info-label">Original Product:</span>
            <span class="info-value" id="detail-original-product">-</span>
          </div>
          <div class="info-item">
            <span class="info-label">Original Amount:</span>
            <span class="info-value" id="detail-original-amount">-</span>
          </div>
        </div>
      </div>

      <!-- 3. Return Details Section -->
      <div class="details-section">
        <h4 class="section-title">Return Details</h4>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">Product Returned:</span>
            <span class="info-value" id="detail-returned-product">-</span>
          </div>
          <div class="info-item">
            <span class="info-label">Quantity Returned:</span>
            <span class="info-value" id="detail-returned-quantity">-</span>
          </div>
          <div class="info-item full-width">
            <span class="info-label">Return Reason:</span>
            <span class="info-value" id="detail-return-reason">-</span>
          </div>
          <div class="info-item full-width">
            <span class="info-label">Return Description:</span>
            <span class="info-value" id="detail-return-description">-</span>
          </div>
          <div class="info-item full-width">
            <span class="info-label">Photos:</span>
            <div class="photo-gallery" id="detail-return-photos">
              <!-- Photos will be loaded here -->
            </div>
          </div>
        </div>
      </div>

      <!-- 4. Replacement Information Section (Editable) -->
      <div class="details-section">
        <h4 class="section-title">Replacement Information</h4>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">Replacement Required:</span>
            <span class="info-value">
              <input type="checkbox" id="replacement-required-checkbox" disabled>
              <label for="replacement-required-checkbox" style="margin-left: 8px;">Yes</label>
            </span>
          </div>
          <div class="info-item">
            <span class="info-label">Replacement Product:</span>
            <span class="info-value" id="detail-replacement-product">-</span>
          </div>
          <div class="info-item">
            <span class="info-label">Replacement Order:</span>
            <span class="info-value">
              <a href="#" id="detail-replacement-order-link" class="order-link" target="_blank" style="display: none;">-</a>
              <span id="detail-replacement-order-none" style="color: #999;">Not created</span>
            </span>
          </div>
          <div class="info-item">
            <span class="info-label">Replacement Appointment:</span>
            <span class="info-value">
              <a href="#" id="detail-replacement-appointment-link" class="order-link" target="_blank" style="display: none;">-</a>
              <span id="detail-replacement-appointment-none" style="color: #999;">Not scheduled</span>
            </span>
          </div>
        </div>
      </div>

      <!-- 5. Refund Information Section (Editable) -->
      <div class="details-section">
        <h4 class="section-title">Refund Information</h4>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">Refund Amount:</span>
            <span class="info-value">
              <input type="number" id="refund-amount-input" class="form-control" step="0.01" min="0" style="max-width: 200px;">
            </span>
          </div>
          <div class="info-item">
            <span class="info-label">Refund Method:</span>
            <span class="info-value">
              <select id="refund-method-select" class="form-control" style="max-width: 200px;">
                <option value="">Select method...</option>
                <option value="Original Payment">Original Payment</option>
                <option value="Store Credit">Store Credit</option>
                <option value="Other">Other</option>
              </select>
            </span>
          </div>
          <div class="info-item">
            <span class="info-label">Refund Status:</span>
            <span class="info-value">
              <span class="badge" id="detail-refund-status">-</span>
            </span>
          </div>
          <div class="info-item">
            <span class="info-label">Refund Date:</span>
            <span class="info-value" id="detail-refund-date">-</span>
          </div>
        </div>
      </div>

      <!-- 6. Admin Actions Section -->
      <div class="details-section">
        <h4 class="section-title">Admin Actions</h4>
        <div class="action-buttons">
          <div class="action-buttons-row">
            <button class="btn-primary" id="approve-return-btn">Approve Return</button>
            <button class="btn-danger" id="reject-return-btn">Reject Return</button>
            <button class="btn-success" id="process-refund-btn">Process Refund</button>
            <button class="btn-secondary" id="create-replacement-btn">Create Replacement Order</button>
            <button class="btn-secondary" id="schedule-replacement-btn">Schedule Replacement Installation</button>
          </div>
          <div class="action-group" style="margin-top: 15px;">
            <label for="update-status-select">Update Status:</label>
            <select id="update-status-select" class="form-control">
              <option value="">Select status...</option>
              <option value="Pending">Pending</option>
              <option value="Approved">Approved</option>
              <option value="Rejected">Rejected</option>
              <option value="Processing">Processing</option>
              <option value="Completed">Completed</option>
            </select>
            <button class="btn-primary" id="update-status-btn" style="margin-top: 8px;">Update Status</button>
          </div>
          <div class="action-group" style="margin-top: 15px;">
            <label for="admin-notes-textarea">Admin Notes:</label>
            <textarea id="admin-notes-textarea" class="form-control" rows="3" placeholder="Add internal notes..."></textarea>
            <button class="btn-primary" id="save-notes-btn" style="margin-top: 8px;">Save Notes</button>
          </div>
          <div id="rejection-reason-group" style="display: none; margin-top: 15px;">
            <label for="rejection-reason-textarea">Rejection Reason:</label>
            <textarea id="rejection-reason-textarea" class="form-control" rows="3" placeholder="Enter reason for rejection..." required></textarea>
            <button class="btn-danger" id="confirm-reject-btn" style="margin-top: 8px;">Confirm Rejection</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Action Menu Dropdown -->
<div id="actionMenu" class="action-menu hidden">
  <ul>
    <li><a href="#" class="action-view">View Details</a></li>
    <li><a href="#" class="action-approve">Approve</a></li>
    <li><a href="#" class="action-reject">Reject</a></li>
    <li><a href="#" class="action-process-refund">Process Refund</a></li>
    <li><a href="#" class="action-create-replacement">Create Replacement</a></li>
  </ul>
</div>
